CREATE TABLE IF NOT EXISTS uuser (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login TEXT
        CONSTRAINT valid_login_format CHECK (
            login ~* '^[A-Za-z0-9._-]{3,30}$'
        )
        CONSTRAINT login_length CHECK (LENGTH(login) <= 255) NOT NULL UNIQUE,
    first_name TEXT
        CONSTRAINT applicant_first_name_length CHECK (LENGTH(first_name) <= 30) NOT NULL,
    last_name TEXT
        CONSTRAINT applicant_last_name_length CHECK (LENGTH(last_name) <= 30) NOT NULL,
    password_hashed bytea
        CONSTRAINT password_hashed_length CHECK (OCTET_LENGTH(password_hashed) <= 32) NOT NULL,
    password_salt bytea
        CONSTRAINT password_salt_length CHECK (OCTET_LENGTH(password_salt) <= 8) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);